// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sf/substreams/foundational-store/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseCode int32

const (
	ResponseCode_RESPONSE_CODE_UNSPECIFIED                 ResponseCode = 0
	ResponseCode_RESPONSE_CODE_FOUND                       ResponseCode = 1
	ResponseCode_RESPONSE_CODE_NOT_FOUND                   ResponseCode = 2
	ResponseCode_RESPONSE_CODE_NOT_FOUND_FINALIZE          ResponseCode = 4
	ResponseCode_RESPONSE_CODE_NOT_FOUND_BLOCK_NOT_REACHED ResponseCode = 5
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0: "RESPONSE_CODE_UNSPECIFIED",
		1: "RESPONSE_CODE_FOUND",
		2: "RESPONSE_CODE_NOT_FOUND",
		4: "RESPONSE_CODE_NOT_FOUND_FINALIZE",
		5: "RESPONSE_CODE_NOT_FOUND_BLOCK_NOT_REACHED",
	}
	ResponseCode_value = map[string]int32{
		"RESPONSE_CODE_UNSPECIFIED":                 0,
		"RESPONSE_CODE_FOUND":                       1,
		"RESPONSE_CODE_NOT_FOUND":                   2,
		"RESPONSE_CODE_NOT_FOUND_FINALIZE":          4,
		"RESPONSE_CODE_NOT_FOUND_BLOCK_NOT_REACHED": 5,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_substreams_foundational_store_v1_service_proto_enumTypes[0].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_sf_substreams_foundational_store_v1_service_proto_enumTypes[0]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_v1_service_proto_rawDescGZIP(), []int{0}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	OmitDeleted   bool                   `protobuf:"varint,3,opt,name=omit_deleted,json=omitDeleted,proto3" json:"omit_deleted,omitempty"`
	Key           []byte                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_sf_substreams_foundational_store_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *GetRequest) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *GetRequest) GetOmitDeleted() bool {
	if x != nil {
		return x.OmitDeleted
	}
	return false
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      ResponseCode           `protobuf:"varint,4,opt,name=response,proto3,enum=foundational_store.ResponseCode" json:"response,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_sf_substreams_foundational_store_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetResponse() ResponseCode {
	if x != nil {
		return x.Response
	}
	return ResponseCode_RESPONSE_CODE_UNSPECIFIED
}

func (x *GetResponse) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	OmitDeleted   bool                   `protobuf:"varint,3,opt,name=omit_deleted,json=omitDeleted,proto3" json:"omit_deleted,omitempty"`
	Keys          [][]byte               `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_sf_substreams_foundational_store_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *GetAllRequest) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *GetAllRequest) GetOmitDeleted() bool {
	if x != nil {
		return x.OmitDeleted
	}
	return false
}

func (x *GetAllRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type ResponseEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Response      *GetResponse           `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseEntry) Reset() {
	*x = ResponseEntry{}
	mi := &file_sf_substreams_foundational_store_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEntry) ProtoMessage() {}

func (x *ResponseEntry) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEntry.ProtoReflect.Descriptor instead.
func (*ResponseEntry) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseEntry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ResponseEntry) GetResponse() *GetResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*ResponseEntry       `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_sf_substreams_foundational_store_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllResponse) GetEntries() []*ResponseEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_sf_substreams_foundational_store_v1_service_proto protoreflect.FileDescriptor

const file_sf_substreams_foundational_store_v1_service_proto_rawDesc = "" +
	"\n" +
	"1sf/substreams/foundational-store/v1/service.proto\x12\x12foundational_store\x1a\x19google/protobuf/any.proto\"\x83\x01\n" +
	"\n" +
	"GetRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12!\n" +
	"\fomit_deleted\x18\x03 \x01(\bR\vomitDeleted\x12\x10\n" +
	"\x03key\x18\x04 \x01(\fR\x03key\"w\n" +
	"\vGetResponse\x12<\n" +
	"\bresponse\x18\x04 \x01(\x0e2 .foundational_store.ResponseCodeR\bresponse\x12*\n" +
	"\x05value\x18\x05 \x01(\v2\x14.google.protobuf.AnyR\x05value\"\x88\x01\n" +
	"\rGetAllRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x02 \x01(\fR\tblockHash\x12!\n" +
	"\fomit_deleted\x18\x03 \x01(\bR\vomitDeleted\x12\x12\n" +
	"\x04keys\x18\x04 \x03(\fR\x04keys\"^\n" +
	"\rResponseEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12;\n" +
	"\bresponse\x18\x02 \x01(\v2\x1f.foundational_store.GetResponseR\bresponse\"M\n" +
	"\x0eGetAllResponse\x12;\n" +
	"\aentries\x18\x01 \x03(\v2!.foundational_store.ResponseEntryR\aentries*\xb8\x01\n" +
	"\fResponseCode\x12\x1d\n" +
	"\x19RESPONSE_CODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RESPONSE_CODE_FOUND\x10\x01\x12\x1b\n" +
	"\x17RESPONSE_CODE_NOT_FOUND\x10\x02\x12$\n" +
	" RESPONSE_CODE_NOT_FOUND_FINALIZE\x10\x04\x12-\n" +
	")RESPONSE_CODE_NOT_FOUND_BLOCK_NOT_REACHED\x10\x052\xa2\x01\n" +
	"\aStoreKV\x12F\n" +
	"\x03Get\x12\x1e.foundational_store.GetRequest\x1a\x1f.foundational_store.GetResponse\x12O\n" +
	"\x06GetAll\x12!.foundational_store.GetAllRequest\x1a\".foundational_store.GetAllResponseB\xe9\x01\n" +
	"\x16com.foundational_storeB\fServiceProtoP\x01Z]github.com/streamingfast/substreams-foundational-store/pb/sf/substreams/foundational-store/v1\xa2\x02\x03FXX\xaa\x02\x11FoundationalStore\xca\x02\x11FoundationalStore\xe2\x02\x1dFoundationalStore\\GPBMetadata\xea\x02\x11FoundationalStoreb\x06proto3"

var (
	file_sf_substreams_foundational_store_v1_service_proto_rawDescOnce sync.Once
	file_sf_substreams_foundational_store_v1_service_proto_rawDescData []byte
)

func file_sf_substreams_foundational_store_v1_service_proto_rawDescGZIP() []byte {
	file_sf_substreams_foundational_store_v1_service_proto_rawDescOnce.Do(func() {
		file_sf_substreams_foundational_store_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_substreams_foundational_store_v1_service_proto_rawDesc), len(file_sf_substreams_foundational_store_v1_service_proto_rawDesc)))
	})
	return file_sf_substreams_foundational_store_v1_service_proto_rawDescData
}

var file_sf_substreams_foundational_store_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sf_substreams_foundational_store_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sf_substreams_foundational_store_v1_service_proto_goTypes = []any{
	(ResponseCode)(0),      // 0: foundational_store.ResponseCode
	(*GetRequest)(nil),     // 1: foundational_store.GetRequest
	(*GetResponse)(nil),    // 2: foundational_store.GetResponse
	(*GetAllRequest)(nil),  // 3: foundational_store.GetAllRequest
	(*ResponseEntry)(nil),  // 4: foundational_store.ResponseEntry
	(*GetAllResponse)(nil), // 5: foundational_store.GetAllResponse
	(*anypb.Any)(nil),      // 6: google.protobuf.Any
}
var file_sf_substreams_foundational_store_v1_service_proto_depIdxs = []int32{
	0, // 0: foundational_store.GetResponse.response:type_name -> foundational_store.ResponseCode
	6, // 1: foundational_store.GetResponse.value:type_name -> google.protobuf.Any
	2, // 2: foundational_store.ResponseEntry.response:type_name -> foundational_store.GetResponse
	4, // 3: foundational_store.GetAllResponse.entries:type_name -> foundational_store.ResponseEntry
	1, // 4: foundational_store.StoreKV.Get:input_type -> foundational_store.GetRequest
	3, // 5: foundational_store.StoreKV.GetAll:input_type -> foundational_store.GetAllRequest
	2, // 6: foundational_store.StoreKV.Get:output_type -> foundational_store.GetResponse
	5, // 7: foundational_store.StoreKV.GetAll:output_type -> foundational_store.GetAllResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sf_substreams_foundational_store_v1_service_proto_init() }
func file_sf_substreams_foundational_store_v1_service_proto_init() {
	if File_sf_substreams_foundational_store_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_substreams_foundational_store_v1_service_proto_rawDesc), len(file_sf_substreams_foundational_store_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sf_substreams_foundational_store_v1_service_proto_goTypes,
		DependencyIndexes: file_sf_substreams_foundational_store_v1_service_proto_depIdxs,
		EnumInfos:         file_sf_substreams_foundational_store_v1_service_proto_enumTypes,
		MessageInfos:      file_sf_substreams_foundational_store_v1_service_proto_msgTypes,
	}.Build()
	File_sf_substreams_foundational_store_v1_service_proto = out.File
	file_sf_substreams_foundational_store_v1_service_proto_goTypes = nil
	file_sf_substreams_foundational_store_v1_service_proto_depIdxs = nil
}
