// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sf/substreams/foundational-store/v1/test.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountOwner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mint          []byte                 `protobuf:"bytes,1,opt,name=mint,proto3" json:"mint,omitempty"`
	Owner         []byte                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountOwner) Reset() {
	*x = AccountOwner{}
	mi := &file_sf_substreams_foundational_store_v1_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountOwner) ProtoMessage() {}

func (x *AccountOwner) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_v1_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountOwner.ProtoReflect.Descriptor instead.
func (*AccountOwner) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_v1_test_proto_rawDescGZIP(), []int{0}
}

func (x *AccountOwner) GetMint() []byte {
	if x != nil {
		return x.Mint
	}
	return nil
}

func (x *AccountOwner) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

var File_sf_substreams_foundational_store_v1_test_proto protoreflect.FileDescriptor

const file_sf_substreams_foundational_store_v1_test_proto_rawDesc = "" +
	"\n" +
	".sf/substreams/foundational-store/v1/test.proto\x12\x12foundational_store\"8\n" +
	"\fAccountOwner\x12\x12\n" +
	"\x04mint\x18\x01 \x01(\fR\x04mint\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\fR\x05ownerB\xe6\x01\n" +
	"\x16com.foundational_storeB\tTestProtoP\x01Z]github.com/streamingfast/substreams-foundational-store/pb/sf/substreams/foundational-store/v1\xa2\x02\x03FXX\xaa\x02\x11FoundationalStore\xca\x02\x11FoundationalStore\xe2\x02\x1dFoundationalStore\\GPBMetadata\xea\x02\x11FoundationalStoreb\x06proto3"

var (
	file_sf_substreams_foundational_store_v1_test_proto_rawDescOnce sync.Once
	file_sf_substreams_foundational_store_v1_test_proto_rawDescData []byte
)

func file_sf_substreams_foundational_store_v1_test_proto_rawDescGZIP() []byte {
	file_sf_substreams_foundational_store_v1_test_proto_rawDescOnce.Do(func() {
		file_sf_substreams_foundational_store_v1_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_substreams_foundational_store_v1_test_proto_rawDesc), len(file_sf_substreams_foundational_store_v1_test_proto_rawDesc)))
	})
	return file_sf_substreams_foundational_store_v1_test_proto_rawDescData
}

var file_sf_substreams_foundational_store_v1_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sf_substreams_foundational_store_v1_test_proto_goTypes = []any{
	(*AccountOwner)(nil), // 0: foundational_store.AccountOwner
}
var file_sf_substreams_foundational_store_v1_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sf_substreams_foundational_store_v1_test_proto_init() }
func file_sf_substreams_foundational_store_v1_test_proto_init() {
	if File_sf_substreams_foundational_store_v1_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_substreams_foundational_store_v1_test_proto_rawDesc), len(file_sf_substreams_foundational_store_v1_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_substreams_foundational_store_v1_test_proto_goTypes,
		DependencyIndexes: file_sf_substreams_foundational_store_v1_test_proto_depIdxs,
		MessageInfos:      file_sf_substreams_foundational_store_v1_test_proto_msgTypes,
	}.Build()
	File_sf_substreams_foundational_store_v1_test_proto = out.File
	file_sf_substreams_foundational_store_v1_test_proto_goTypes = nil
	file_sf_substreams_foundational_store_v1_test_proto_depIdxs = nil
}
