// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sf/substreams/foundational-store/v1/type.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_sf_substreams_foundational_store_v1_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_v1_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_v1_type_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Entry) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type Entries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entries) Reset() {
	*x = Entries{}
	mi := &file_sf_substreams_foundational_store_v1_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entries) ProtoMessage() {}

func (x *Entries) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_v1_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entries.ProtoReflect.Descriptor instead.
func (*Entries) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_v1_type_proto_rawDescGZIP(), []int{1}
}

func (x *Entries) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_sf_substreams_foundational_store_v1_type_proto protoreflect.FileDescriptor

const file_sf_substreams_foundational_store_v1_type_proto_rawDesc = "" +
	"\n" +
	".sf/substreams/foundational-store/v1/type.proto\x12\x12foundational_store\x1a\x19google/protobuf/any.proto\"E\n" +
	"\x05Entry\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12*\n" +
	"\x05value\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x05value\">\n" +
	"\aEntries\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.foundational_store.EntryR\aentriesB\xe6\x01\n" +
	"\x16com.foundational_storeB\tTypeProtoP\x01Z]github.com/streamingfast/substreams-foundational-store/pb/sf/substreams/foundational-store/v1\xa2\x02\x03FXX\xaa\x02\x11FoundationalStore\xca\x02\x11FoundationalStore\xe2\x02\x1dFoundationalStore\\GPBMetadata\xea\x02\x11FoundationalStoreb\x06proto3"

var (
	file_sf_substreams_foundational_store_v1_type_proto_rawDescOnce sync.Once
	file_sf_substreams_foundational_store_v1_type_proto_rawDescData []byte
)

func file_sf_substreams_foundational_store_v1_type_proto_rawDescGZIP() []byte {
	file_sf_substreams_foundational_store_v1_type_proto_rawDescOnce.Do(func() {
		file_sf_substreams_foundational_store_v1_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_substreams_foundational_store_v1_type_proto_rawDesc), len(file_sf_substreams_foundational_store_v1_type_proto_rawDesc)))
	})
	return file_sf_substreams_foundational_store_v1_type_proto_rawDescData
}

var file_sf_substreams_foundational_store_v1_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sf_substreams_foundational_store_v1_type_proto_goTypes = []any{
	(*Entry)(nil),     // 0: foundational_store.Entry
	(*Entries)(nil),   // 1: foundational_store.Entries
	(*anypb.Any)(nil), // 2: google.protobuf.Any
}
var file_sf_substreams_foundational_store_v1_type_proto_depIdxs = []int32{
	2, // 0: foundational_store.Entry.value:type_name -> google.protobuf.Any
	0, // 1: foundational_store.Entries.entries:type_name -> foundational_store.Entry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sf_substreams_foundational_store_v1_type_proto_init() }
func file_sf_substreams_foundational_store_v1_type_proto_init() {
	if File_sf_substreams_foundational_store_v1_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_substreams_foundational_store_v1_type_proto_rawDesc), len(file_sf_substreams_foundational_store_v1_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_substreams_foundational_store_v1_type_proto_goTypes,
		DependencyIndexes: file_sf_substreams_foundational_store_v1_type_proto_depIdxs,
		MessageInfos:      file_sf_substreams_foundational_store_v1_type_proto_msgTypes,
	}.Build()
	File_sf_substreams_foundational_store_v1_type_proto = out.File
	file_sf_substreams_foundational_store_v1_type_proto_goTypes = nil
	file_sf_substreams_foundational_store_v1_type_proto_depIdxs = nil
}
