syntax = "proto3";
import "google/protobuf/any.proto";
package sf.substreams.foundational_store.v1;
option go_package = "github.com/streamingfast/substreams-foundational-store/pb/sf/substreams/foundational-store/v1;pbstore";
service Store {
  rpc Get(GetRequest) returns (GetResponse);
  rpc GetAll(GetAllRequest) returns (GetAllResponse);
}
message GetRequest {
  uint64 block_number = 1;
  bytes block_hash = 2;
  bool omit_deleted = 3;
  bytes key = 4;
}
message GetResponse {
  ResponseCode response = 4;
  google.protobuf.Any value = 5;
}
message GetAllRequest {
  uint64 block_number = 1;
  bytes block_hash = 2;
  bool omit_deleted = 3;
  repeated bytes keys = 4;
}
message ResponseEntry {
  bytes key = 1;
  GetResponse response = 2;
}
message GetAllResponse {
  repeated ResponseEntry entries= 1;
}
enum ResponseCode {
  RESPONSE_CODE_UNSPECIFIED = 0;
  RESPONSE_CODE_FOUND = 1;
  RESPONSE_CODE_NOT_FOUND = 2;
  RESPONSE_CODE_NOT_FOUND_FINALIZE = 4;
  RESPONSE_CODE_NOT_FOUND_BLOCK_NOT_REACHED = 5;
}
message Entry {
  bytes                 key   = 2;
  google.protobuf.Any   value = 4;
}
message Entries {
  repeated Entry entries = 1;
}
