syntax = "proto3";

import "google/protobuf/any.proto";

import "sf/substreams/foundational-store/model/v2/model.proto";

package sf.substreams.foundational_store.service.v2;

option go_package = "github.com/streamingfast/substreams-foundational-store/pb/sf/substreams/foundational-store/service/v2;pbservice";

service Store {
  rpc Get(GetRequest) returns (GetResponse);
  rpc GetFirst(GetRequest) returns (GetResponse);
}


message GetRequest {
  uint64 block_number = 1;
  bytes block_hash = 2;
  repeated model.v2.Key keys = 3;
}

message GetResponse {
  bool block_reached = 1;
  model.v2.QueriedEntries entries = 2;
}