// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: store/service.proto

package store

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StoreKVClient is the client API for StoreKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreKVClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
}

type storeKVClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreKVClient(cc grpc.ClientConnInterface) StoreKVClient {
	return &storeKVClient{cc}
}

func (c *storeKVClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/StoreKV/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeKVClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/StoreKV/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreKVServer is the server API for StoreKV service.
// All implementations must embed UnimplementedStoreKVServer
// for forward compatibility
type StoreKVServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	mustEmbedUnimplementedStoreKVServer()
}

// UnimplementedStoreKVServer must be embedded to have forward compatible implementations.
type UnimplementedStoreKVServer struct {
}

func (UnimplementedStoreKVServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStoreKVServer) GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedStoreKVServer) mustEmbedUnimplementedStoreKVServer() {}

// UnsafeStoreKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreKVServer will
// result in compilation errors.
type UnsafeStoreKVServer interface {
	mustEmbedUnimplementedStoreKVServer()
}

func RegisterStoreKVServer(s grpc.ServiceRegistrar, srv StoreKVServer) {
	s.RegisterService(&StoreKV_ServiceDesc, srv)
}

func _StoreKV_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreKVServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StoreKV/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreKVServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreKV_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreKVServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StoreKV/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreKVServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoreKV_ServiceDesc is the grpc.ServiceDesc for StoreKV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreKV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "StoreKV",
	HandlerType: (*StoreKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _StoreKV_Get_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _StoreKV_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store/service.proto",
}
