// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: sf/substreams/foundational-store-management/router/v2/router.proto

package pbrouter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StoreManagerClient is the client API for StoreManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreManagerClient interface {
	// start the store process and call router.Register when started and reader to server
	DeployStore(ctx context.Context, in *DeployStoreRequest, opts ...grpc.CallOption) (*DeployStoreResponse, error)
	// stop the store process and call router.UnRegister when stopped
	UndeployStore(ctx context.Context, in *UndeployStoreRequest, opts ...grpc.CallOption) (*UndeployStoreResponse, error)
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type storeManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreManagerClient(cc grpc.ClientConnInterface) StoreManagerClient {
	return &storeManagerClient{cc}
}

func (c *storeManagerClient) DeployStore(ctx context.Context, in *DeployStoreRequest, opts ...grpc.CallOption) (*DeployStoreResponse, error) {
	out := new(DeployStoreResponse)
	err := c.cc.Invoke(ctx, "/sf.substreams.foundational_store_management.router.v2.StoreManager/DeployStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeManagerClient) UndeployStore(ctx context.Context, in *UndeployStoreRequest, opts ...grpc.CallOption) (*UndeployStoreResponse, error) {
	out := new(UndeployStoreResponse)
	err := c.cc.Invoke(ctx, "/sf.substreams.foundational_store_management.router.v2.StoreManager/UndeployStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeManagerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/sf.substreams.foundational_store_management.router.v2.StoreManager/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreManagerServer is the server API for StoreManager service.
// All implementations must embed UnimplementedStoreManagerServer
// for forward compatibility
type StoreManagerServer interface {
	// start the store process and call router.Register when started and reader to server
	DeployStore(context.Context, *DeployStoreRequest) (*DeployStoreResponse, error)
	// stop the store process and call router.UnRegister when stopped
	UndeployStore(context.Context, *UndeployStoreRequest) (*UndeployStoreResponse, error)
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedStoreManagerServer()
}

// UnimplementedStoreManagerServer must be embedded to have forward compatible implementations.
type UnimplementedStoreManagerServer struct {
}

func (UnimplementedStoreManagerServer) DeployStore(context.Context, *DeployStoreRequest) (*DeployStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeployStore not implemented")
}
func (UnimplementedStoreManagerServer) UndeployStore(context.Context, *UndeployStoreRequest) (*UndeployStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndeployStore not implemented")
}
func (UnimplementedStoreManagerServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedStoreManagerServer) mustEmbedUnimplementedStoreManagerServer() {}

// UnsafeStoreManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreManagerServer will
// result in compilation errors.
type UnsafeStoreManagerServer interface {
	mustEmbedUnimplementedStoreManagerServer()
}

func RegisterStoreManagerServer(s grpc.ServiceRegistrar, srv StoreManagerServer) {
	s.RegisterService(&StoreManager_ServiceDesc, srv)
}

func _StoreManager_DeployStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeployStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreManagerServer).DeployStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sf.substreams.foundational_store_management.router.v2.StoreManager/DeployStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreManagerServer).DeployStore(ctx, req.(*DeployStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreManager_UndeployStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndeployStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreManagerServer).UndeployStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sf.substreams.foundational_store_management.router.v2.StoreManager/UndeployStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreManagerServer).UndeployStore(ctx, req.(*UndeployStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreManager_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreManagerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sf.substreams.foundational_store_management.router.v2.StoreManager/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreManagerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoreManager_ServiceDesc is the grpc.ServiceDesc for StoreManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sf.substreams.foundational_store_management.router.v2.StoreManager",
	HandlerType: (*StoreManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeployStore",
			Handler:    _StoreManager_DeployStore_Handler,
		},
		{
			MethodName: "UndeployStore",
			Handler:    _StoreManager_UndeployStore_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _StoreManager_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sf/substreams/foundational-store-management/router/v2/router.proto",
}

// RouterClient is the client API for Router service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouterClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetFirst(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type routerClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterClient(cc grpc.ClientConnInterface) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/sf.substreams.foundational_store_management.router.v2.Router/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetFirst(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/sf.substreams.foundational_store_management.router.v2.Router/GetFirst", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServer is the server API for Router service.
// All implementations must embed UnimplementedRouterServer
// for forward compatibility
type RouterServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetFirst(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedRouterServer()
}

// UnimplementedRouterServer must be embedded to have forward compatible implementations.
type UnimplementedRouterServer struct {
}

func (UnimplementedRouterServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRouterServer) GetFirst(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFirst not implemented")
}
func (UnimplementedRouterServer) mustEmbedUnimplementedRouterServer() {}

// UnsafeRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterServer will
// result in compilation errors.
type UnsafeRouterServer interface {
	mustEmbedUnimplementedRouterServer()
}

func RegisterRouterServer(s grpc.ServiceRegistrar, srv RouterServer) {
	s.RegisterService(&Router_ServiceDesc, srv)
}

func _Router_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sf.substreams.foundational_store_management.router.v2.Router/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetFirst_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetFirst(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sf.substreams.foundational_store_management.router.v2.Router/GetFirst",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetFirst(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Router_ServiceDesc is the grpc.ServiceDesc for Router service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Router_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sf.substreams.foundational_store_management.router.v2.Router",
	HandlerType: (*RouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Router_Get_Handler,
		},
		{
			MethodName: "GetFirst",
			Handler:    _Router_GetFirst_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sf/substreams/foundational-store-management/router/v2/router.proto",
}
