// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: sf/substreams/foundational-store-management/router/v2/router.proto

package pbrouter

import (
	v2 "github.com/streamingfast/substreams-foundational-store/pb/sf/substreams/foundational-store/service/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingResponse_Code int32

const (
	PingResponse_unset  PingResponse_Code = 0
	PingResponse_pong   PingResponse_Code = 1
	PingResponse_failed PingResponse_Code = 2
)

// Enum value maps for PingResponse_Code.
var (
	PingResponse_Code_name = map[int32]string{
		0: "unset",
		1: "pong",
		2: "failed",
	}
	PingResponse_Code_value = map[string]int32{
		"unset":  0,
		"pong":   1,
		"failed": 2,
	}
)

func (x PingResponse_Code) Enum() *PingResponse_Code {
	p := new(PingResponse_Code)
	*p = x
	return p
}

func (x PingResponse_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PingResponse_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_enumTypes[0].Descriptor()
}

func (PingResponse_Code) Type() protoreflect.EnumType {
	return &file_sf_substreams_foundational_store_management_router_v2_router_proto_enumTypes[0]
}

func (x PingResponse_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PingResponse_Code.Descriptor instead.
func (PingResponse_Code) EnumDescriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{1, 0}
}

type GetResponse_Code int32

const (
	GetResponse_unset   GetResponse_Code = 0
	GetResponse_success GetResponse_Code = 1
	GetResponse_failed  GetResponse_Code = 2
)

// Enum value maps for GetResponse_Code.
var (
	GetResponse_Code_name = map[int32]string{
		0: "unset",
		1: "success",
		2: "failed",
	}
	GetResponse_Code_value = map[string]int32{
		"unset":   0,
		"success": 1,
		"failed":  2,
	}
)

func (x GetResponse_Code) Enum() *GetResponse_Code {
	p := new(GetResponse_Code)
	*p = x
	return p
}

func (x GetResponse_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetResponse_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_enumTypes[1].Descriptor()
}

func (GetResponse_Code) Type() protoreflect.EnumType {
	return &file_sf_substreams_foundational_store_management_router_v2_router_proto_enumTypes[1]
}

func (x GetResponse_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetResponse_Code.Descriptor instead.
func (GetResponse_Code) EnumDescriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{3, 0}
}

type DeployStoreResponse_Code int32

const (
	DeployStoreResponse_unset  DeployStoreResponse_Code = 0
	DeployStoreResponse_deploy DeployStoreResponse_Code = 1
	DeployStoreResponse_failed DeployStoreResponse_Code = 3
)

// Enum value maps for DeployStoreResponse_Code.
var (
	DeployStoreResponse_Code_name = map[int32]string{
		0: "unset",
		1: "deploy",
		3: "failed",
	}
	DeployStoreResponse_Code_value = map[string]int32{
		"unset":  0,
		"deploy": 1,
		"failed": 3,
	}
)

func (x DeployStoreResponse_Code) Enum() *DeployStoreResponse_Code {
	p := new(DeployStoreResponse_Code)
	*p = x
	return p
}

func (x DeployStoreResponse_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeployStoreResponse_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_enumTypes[2].Descriptor()
}

func (DeployStoreResponse_Code) Type() protoreflect.EnumType {
	return &file_sf_substreams_foundational_store_management_router_v2_router_proto_enumTypes[2]
}

func (x DeployStoreResponse_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeployStoreResponse_Code.Descriptor instead.
func (DeployStoreResponse_Code) EnumDescriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{7, 0}
}

type UndeployStoreResponse_Code int32

const (
	UndeployStoreResponse_unset    UndeployStoreResponse_Code = 0
	UndeployStoreResponse_undeploy UndeployStoreResponse_Code = 1
	UndeployStoreResponse_failed   UndeployStoreResponse_Code = 2
)

// Enum value maps for UndeployStoreResponse_Code.
var (
	UndeployStoreResponse_Code_name = map[int32]string{
		0: "unset",
		1: "undeploy",
		2: "failed",
	}
	UndeployStoreResponse_Code_value = map[string]int32{
		"unset":    0,
		"undeploy": 1,
		"failed":   2,
	}
)

func (x UndeployStoreResponse_Code) Enum() *UndeployStoreResponse_Code {
	p := new(UndeployStoreResponse_Code)
	*p = x
	return p
}

func (x UndeployStoreResponse_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UndeployStoreResponse_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_enumTypes[3].Descriptor()
}

func (UndeployStoreResponse_Code) Type() protoreflect.EnumType {
	return &file_sf_substreams_foundational_store_management_router_v2_router_proto_enumTypes[3]
}

func (x UndeployStoreResponse_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UndeployStoreResponse_Code.Descriptor instead.
func (UndeployStoreResponse_Code) EnumDescriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{9, 0}
}

type Server_State int32

const (
	Server_unset         Server_State = 0
	Server_deployed      Server_State = 2
	Server_ready         Server_State = 1
	Server_shutting_down Server_State = 3
	Server_not_ready     Server_State = 4
	Server_falling       Server_State = 5
)

// Enum value maps for Server_State.
var (
	Server_State_name = map[int32]string{
		0: "unset",
		2: "deployed",
		1: "ready",
		3: "shutting_down",
		4: "not_ready",
		5: "falling",
	}
	Server_State_value = map[string]int32{
		"unset":         0,
		"deployed":      2,
		"ready":         1,
		"shutting_down": 3,
		"not_ready":     4,
		"falling":       5,
	}
)

func (x Server_State) Enum() *Server_State {
	p := new(Server_State)
	*p = x
	return p
}

func (x Server_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Server_State) Descriptor() protoreflect.EnumDescriptor {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_enumTypes[4].Descriptor()
}

func (Server_State) Type() protoreflect.EnumType {
	return &file_sf_substreams_foundational_store_management_router_v2_router_proto_enumTypes[4]
}

func (x Server_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Server_State.Descriptor instead.
func (Server_State) EnumDescriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{10, 0}
}

type PingRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModuleOutputHash string                 `protobuf:"bytes,1,opt,name=module_output_hash,json=moduleOutputHash,proto3" json:"module_output_hash,omitempty"`
	Network          string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetModuleOutputHash() string {
	if x != nil {
		return x.ModuleOutputHash
	}
	return ""
}

func (x *PingRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          PingResponse_Code      `protobuf:"varint,1,opt,name=code,proto3,enum=sf.substreams.foundational_store_management.router.v2.PingResponse_Code" json:"code,omitempty"`
	FailureReason *string                `protobuf:"bytes,2,opt,name=failureReason,proto3,oneof" json:"failureReason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetCode() PingResponse_Code {
	if x != nil {
		return x.Code
	}
	return PingResponse_unset
}

func (x *PingResponse) GetFailureReason() string {
	if x != nil && x.FailureReason != nil {
		return *x.FailureReason
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *v2.GetRequest         `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Store         *Store                 `protobuf:"bytes,2,opt,name=store,proto3" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetRequest() *v2.GetRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GetRequest) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Code          GetResponse_Code       `protobuf:"varint,2,opt,name=code,proto3,enum=sf.substreams.foundational_store_management.router.v2.GetResponse_Code" json:"code,omitempty"`
	FailureReason *string                `protobuf:"bytes,3,opt,name=failureReason,proto3,oneof" json:"failureReason,omitempty"`
	StoreResponse *v2.GetResponse        `protobuf:"bytes,4,opt,name=store_response,json=storeResponse,proto3" json:"store_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *GetResponse) GetCode() GetResponse_Code {
	if x != nil {
		return x.Code
	}
	return GetResponse_unset
}

func (x *GetResponse) GetFailureReason() string {
	if x != nil && x.FailureReason != nil {
		return *x.FailureReason
	}
	return ""
}

func (x *GetResponse) GetStoreResponse() *v2.GetResponse {
	if x != nil {
		return x.StoreResponse
	}
	return nil
}

type LookupRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModuleOutputHash string                 `protobuf:"bytes,1,opt,name=module_output_hash,json=moduleOutputHash,proto3" json:"module_output_hash,omitempty"`
	Network          string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{4}
}

func (x *LookupRequest) GetModuleOutputHash() string {
	if x != nil {
		return x.ModuleOutputHash
	}
	return ""
}

func (x *LookupRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{5}
}

func (x *LookupResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type DeployStoreRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Store              *Store                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	SubstreamsEndpoint string                 `protobuf:"bytes,2,opt,name=substreams_endpoint,json=substreamsEndpoint,proto3" json:"substreams_endpoint,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeployStoreRequest) Reset() {
	*x = DeployStoreRequest{}
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployStoreRequest) ProtoMessage() {}

func (x *DeployStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployStoreRequest.ProtoReflect.Descriptor instead.
func (*DeployStoreRequest) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{6}
}

func (x *DeployStoreRequest) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

func (x *DeployStoreRequest) GetSubstreamsEndpoint() string {
	if x != nil {
		return x.SubstreamsEndpoint
	}
	return ""
}

type DeployStoreResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Code          DeployStoreResponse_Code `protobuf:"varint,1,opt,name=code,proto3,enum=sf.substreams.foundational_store_management.router.v2.DeployStoreResponse_Code" json:"code,omitempty"`
	FailureReason *string                  `protobuf:"bytes,2,opt,name=failureReason,proto3,oneof" json:"failureReason,omitempty"`
	Server        *Server                  `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployStoreResponse) Reset() {
	*x = DeployStoreResponse{}
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployStoreResponse) ProtoMessage() {}

func (x *DeployStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployStoreResponse.ProtoReflect.Descriptor instead.
func (*DeployStoreResponse) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{7}
}

func (x *DeployStoreResponse) GetCode() DeployStoreResponse_Code {
	if x != nil {
		return x.Code
	}
	return DeployStoreResponse_unset
}

func (x *DeployStoreResponse) GetFailureReason() string {
	if x != nil && x.FailureReason != nil {
		return *x.FailureReason
	}
	return ""
}

func (x *DeployStoreResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type UndeployStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeployStoreRequest) Reset() {
	*x = UndeployStoreRequest{}
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeployStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeployStoreRequest) ProtoMessage() {}

func (x *UndeployStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeployStoreRequest.ProtoReflect.Descriptor instead.
func (*UndeployStoreRequest) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{8}
}

func (x *UndeployStoreRequest) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type UndeployStoreResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Code          UndeployStoreResponse_Code `protobuf:"varint,1,opt,name=code,proto3,enum=sf.substreams.foundational_store_management.router.v2.UndeployStoreResponse_Code" json:"code,omitempty"`
	FailureReason *string                    `protobuf:"bytes,2,opt,name=failureReason,proto3,oneof" json:"failureReason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndeployStoreResponse) Reset() {
	*x = UndeployStoreResponse{}
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndeployStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndeployStoreResponse) ProtoMessage() {}

func (x *UndeployStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndeployStoreResponse.ProtoReflect.Descriptor instead.
func (*UndeployStoreResponse) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{9}
}

func (x *UndeployStoreResponse) GetCode() UndeployStoreResponse_Code {
	if x != nil {
		return x.Code
	}
	return UndeployStoreResponse_unset
}

func (x *UndeployStoreResponse) GetFailureReason() string {
	if x != nil && x.FailureReason != nil {
		return *x.FailureReason
	}
	return ""
}

type Server struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Address               string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port                  string                 `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	State                 Server_State           `protobuf:"varint,4,opt,name=state,proto3,enum=sf.substreams.foundational_store_management.router.v2.Server_State" json:"state,omitempty"`
	StatefulSetName       string                 `protobuf:"bytes,5,opt,name=stateful_set_name,json=statefulSetName,proto3" json:"stateful_set_name,omitempty"`
	LastPingTime          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_ping_time,json=lastPingTime,proto3" json:"last_ping_time,omitempty"`
	LastRequest           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_request,json=lastRequest,proto3" json:"last_request,omitempty"`
	LastSuccessfulRequest *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_successful_request,json=lastSuccessfulRequest,proto3" json:"last_successful_request,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{10}
}

func (x *Server) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Server) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Server) GetState() Server_State {
	if x != nil {
		return x.State
	}
	return Server_unset
}

func (x *Server) GetStatefulSetName() string {
	if x != nil {
		return x.StatefulSetName
	}
	return ""
}

func (x *Server) GetLastPingTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPingTime
	}
	return nil
}

func (x *Server) GetLastRequest() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRequest
	}
	return nil
}

func (x *Server) GetLastSuccessfulRequest() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSuccessfulRequest
	}
	return nil
}

type Store struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Network           string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	SubstreamsPackage string                 `protobuf:"bytes,4,opt,name=substreams_package,json=substreamsPackage,proto3" json:"substreams_package,omitempty"`
	OutputModule      string                 `protobuf:"bytes,5,opt,name=output_module,json=outputModule,proto3" json:"output_module,omitempty"`
	OutputModuleHash  string                 `protobuf:"bytes,6,opt,name=output_module_hash,json=outputModuleHash,proto3" json:"output_module_hash,omitempty"`
	EntityDataTypeUrl string                 `protobuf:"bytes,7,opt,name=entity_data_type_url,json=entityDataTypeUrl,proto3" json:"entity_data_type_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP(), []int{11}
}

func (x *Store) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Store) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Store) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Store) GetSubstreamsPackage() string {
	if x != nil {
		return x.SubstreamsPackage
	}
	return ""
}

func (x *Store) GetOutputModule() string {
	if x != nil {
		return x.OutputModule
	}
	return ""
}

func (x *Store) GetOutputModuleHash() string {
	if x != nil {
		return x.OutputModuleHash
	}
	return ""
}

func (x *Store) GetEntityDataTypeUrl() string {
	if x != nil {
		return x.EntityDataTypeUrl
	}
	return ""
}

var File_sf_substreams_foundational_store_management_router_v2_router_proto protoreflect.FileDescriptor

const file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDesc = "" +
	"\n" +
	"Bsf/substreams/foundational-store-management/router/v2/router.proto\x125sf.substreams.foundational_store_management.router.v2\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a9sf/substreams/foundational-store/service/v2/service.proto\"U\n" +
	"\vPingRequest\x12,\n" +
	"\x12module_output_hash\x18\x01 \x01(\tR\x10moduleOutputHash\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\"\xd2\x01\n" +
	"\fPingResponse\x12\\\n" +
	"\x04code\x18\x01 \x01(\x0e2H.sf.substreams.foundational_store_management.router.v2.PingResponse.CodeR\x04code\x12)\n" +
	"\rfailureReason\x18\x02 \x01(\tH\x00R\rfailureReason\x88\x01\x01\"'\n" +
	"\x04Code\x12\t\n" +
	"\x05unset\x10\x00\x12\b\n" +
	"\x04pong\x10\x01\x12\n" +
	"\n" +
	"\x06failed\x10\x02B\x10\n" +
	"\x0e_failureReason\"\xb3\x01\n" +
	"\n" +
	"GetRequest\x12Q\n" +
	"\arequest\x18\x01 \x01(\v27.sf.substreams.foundational_store.service.v2.GetRequestR\arequest\x12R\n" +
	"\x05store\x18\x02 \x01(\v2<.sf.substreams.foundational_store_management.router.v2.StoreR\x05store\"\x8b\x03\n" +
	"\vGetResponse\x12U\n" +
	"\x06server\x18\x01 \x01(\v2=.sf.substreams.foundational_store_management.router.v2.ServerR\x06server\x12[\n" +
	"\x04code\x18\x02 \x01(\x0e2G.sf.substreams.foundational_store_management.router.v2.GetResponse.CodeR\x04code\x12)\n" +
	"\rfailureReason\x18\x03 \x01(\tH\x00R\rfailureReason\x88\x01\x01\x12_\n" +
	"\x0estore_response\x18\x04 \x01(\v28.sf.substreams.foundational_store.service.v2.GetResponseR\rstoreResponse\"*\n" +
	"\x04Code\x12\t\n" +
	"\x05unset\x10\x00\x12\v\n" +
	"\asuccess\x10\x01\x12\n" +
	"\n" +
	"\x06failed\x10\x02B\x10\n" +
	"\x0e_failureReason\"W\n" +
	"\rLookupRequest\x12,\n" +
	"\x12module_output_hash\x18\x01 \x01(\tR\x10moduleOutputHash\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\"g\n" +
	"\x0eLookupResponse\x12U\n" +
	"\x06server\x18\x01 \x01(\v2=.sf.substreams.foundational_store_management.router.v2.ServerR\x06server\"\x99\x01\n" +
	"\x12DeployStoreRequest\x12R\n" +
	"\x05store\x18\x01 \x01(\v2<.sf.substreams.foundational_store_management.router.v2.StoreR\x05store\x12/\n" +
	"\x13substreams_endpoint\x18\x02 \x01(\tR\x12substreamsEndpoint\"\xb9\x02\n" +
	"\x13DeployStoreResponse\x12c\n" +
	"\x04code\x18\x01 \x01(\x0e2O.sf.substreams.foundational_store_management.router.v2.DeployStoreResponse.CodeR\x04code\x12)\n" +
	"\rfailureReason\x18\x02 \x01(\tH\x00R\rfailureReason\x88\x01\x01\x12U\n" +
	"\x06server\x18\x03 \x01(\v2=.sf.substreams.foundational_store_management.router.v2.ServerR\x06server\")\n" +
	"\x04Code\x12\t\n" +
	"\x05unset\x10\x00\x12\n" +
	"\n" +
	"\x06deploy\x10\x01\x12\n" +
	"\n" +
	"\x06failed\x10\x03B\x10\n" +
	"\x0e_failureReason\"m\n" +
	"\x14UndeployStoreRequest\x12U\n" +
	"\x06server\x18\x03 \x01(\v2=.sf.substreams.foundational_store_management.router.v2.ServerR\x06server\"\xe8\x01\n" +
	"\x15UndeployStoreResponse\x12e\n" +
	"\x04code\x18\x01 \x01(\x0e2Q.sf.substreams.foundational_store_management.router.v2.UndeployStoreResponse.CodeR\x04code\x12)\n" +
	"\rfailureReason\x18\x02 \x01(\tH\x00R\rfailureReason\x88\x01\x01\"+\n" +
	"\x04Code\x12\t\n" +
	"\x05unset\x10\x00\x12\f\n" +
	"\bundeploy\x10\x01\x12\n" +
	"\n" +
	"\x06failed\x10\x02B\x10\n" +
	"\x0e_failureReason\"\xee\x03\n" +
	"\x06Server\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\tR\x04port\x12Y\n" +
	"\x05state\x18\x04 \x01(\x0e2C.sf.substreams.foundational_store_management.router.v2.Server.StateR\x05state\x12*\n" +
	"\x11stateful_set_name\x18\x05 \x01(\tR\x0fstatefulSetName\x12@\n" +
	"\x0elast_ping_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\flastPingTime\x12=\n" +
	"\flast_request\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vlastRequest\x12R\n" +
	"\x17last_successful_request\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x15lastSuccessfulRequest\"Z\n" +
	"\x05State\x12\t\n" +
	"\x05unset\x10\x00\x12\f\n" +
	"\bdeployed\x10\x02\x12\t\n" +
	"\x05ready\x10\x01\x12\x11\n" +
	"\rshutting_down\x10\x03\x12\r\n" +
	"\tnot_ready\x10\x04\x12\v\n" +
	"\afalling\x10\x05\"\x82\x02\n" +
	"\x05Store\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12-\n" +
	"\x12substreams_package\x18\x04 \x01(\tR\x11substreamsPackage\x12#\n" +
	"\routput_module\x18\x05 \x01(\tR\foutputModule\x12,\n" +
	"\x12output_module_hash\x18\x06 \x01(\tR\x10outputModuleHash\x12/\n" +
	"\x14entity_data_type_url\x18\a \x01(\tR\x11entityDataTypeUrl2\xf4\x03\n" +
	"\fStoreManager\x12\xa4\x01\n" +
	"\vDeployStore\x12I.sf.substreams.foundational_store_management.router.v2.DeployStoreRequest\x1aJ.sf.substreams.foundational_store_management.router.v2.DeployStoreResponse\x12\xaa\x01\n" +
	"\rUndeployStore\x12K.sf.substreams.foundational_store_management.router.v2.UndeployStoreRequest\x1aL.sf.substreams.foundational_store_management.router.v2.UndeployStoreResponse\x12\x8f\x01\n" +
	"\x04Ping\x12B.sf.substreams.foundational_store_management.router.v2.PingRequest\x1aC.sf.substreams.foundational_store_management.router.v2.PingResponse2\xab\x02\n" +
	"\x06Router\x12\x8c\x01\n" +
	"\x03Get\x12A.sf.substreams.foundational_store_management.router.v2.GetRequest\x1aB.sf.substreams.foundational_store_management.router.v2.GetResponse\x12\x91\x01\n" +
	"\bGetFirst\x12A.sf.substreams.foundational_store_management.router.v2.GetRequest\x1aB.sf.substreams.foundational_store_management.router.v2.GetResponseB\xc1\x03\n" +
	"9com.sf.substreams.foundational_store_management.router.v2B\vRouterProtoP\x01Z\x85\x01github.com/streamingfast/substreams-foundational-stores-management/pb/sf/substreams/foundational-stores-management/router/v2;pbrouter\xa2\x02\x04SSFR\xaa\x023Sf.Substreams.FoundationalStoreManagement.Router.V2\xca\x023Sf\\Substreams\\FoundationalStoreManagement\\Router\\V2\xe2\x02?Sf\\Substreams\\FoundationalStoreManagement\\Router\\V2\\GPBMetadata\xea\x027Sf::Substreams::FoundationalStoreManagement::Router::V2b\x06proto3"

var (
	file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescOnce sync.Once
	file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescData []byte
)

func file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescGZIP() []byte {
	file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescOnce.Do(func() {
		file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDesc), len(file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDesc)))
	})
	return file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDescData
}

var file_sf_substreams_foundational_store_management_router_v2_router_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_sf_substreams_foundational_store_management_router_v2_router_proto_goTypes = []any{
	(PingResponse_Code)(0),          // 0: sf.substreams.foundational_store_management.router.v2.PingResponse.Code
	(GetResponse_Code)(0),           // 1: sf.substreams.foundational_store_management.router.v2.GetResponse.Code
	(DeployStoreResponse_Code)(0),   // 2: sf.substreams.foundational_store_management.router.v2.DeployStoreResponse.Code
	(UndeployStoreResponse_Code)(0), // 3: sf.substreams.foundational_store_management.router.v2.UndeployStoreResponse.Code
	(Server_State)(0),               // 4: sf.substreams.foundational_store_management.router.v2.Server.State
	(*PingRequest)(nil),             // 5: sf.substreams.foundational_store_management.router.v2.PingRequest
	(*PingResponse)(nil),            // 6: sf.substreams.foundational_store_management.router.v2.PingResponse
	(*GetRequest)(nil),              // 7: sf.substreams.foundational_store_management.router.v2.GetRequest
	(*GetResponse)(nil),             // 8: sf.substreams.foundational_store_management.router.v2.GetResponse
	(*LookupRequest)(nil),           // 9: sf.substreams.foundational_store_management.router.v2.LookupRequest
	(*LookupResponse)(nil),          // 10: sf.substreams.foundational_store_management.router.v2.LookupResponse
	(*DeployStoreRequest)(nil),      // 11: sf.substreams.foundational_store_management.router.v2.DeployStoreRequest
	(*DeployStoreResponse)(nil),     // 12: sf.substreams.foundational_store_management.router.v2.DeployStoreResponse
	(*UndeployStoreRequest)(nil),    // 13: sf.substreams.foundational_store_management.router.v2.UndeployStoreRequest
	(*UndeployStoreResponse)(nil),   // 14: sf.substreams.foundational_store_management.router.v2.UndeployStoreResponse
	(*Server)(nil),                  // 15: sf.substreams.foundational_store_management.router.v2.Server
	(*Store)(nil),                   // 16: sf.substreams.foundational_store_management.router.v2.Store
	(*v2.GetRequest)(nil),           // 17: sf.substreams.foundational_store.service.v2.GetRequest
	(*v2.GetResponse)(nil),          // 18: sf.substreams.foundational_store.service.v2.GetResponse
	(*timestamppb.Timestamp)(nil),   // 19: google.protobuf.Timestamp
}
var file_sf_substreams_foundational_store_management_router_v2_router_proto_depIdxs = []int32{
	0,  // 0: sf.substreams.foundational_store_management.router.v2.PingResponse.code:type_name -> sf.substreams.foundational_store_management.router.v2.PingResponse.Code
	17, // 1: sf.substreams.foundational_store_management.router.v2.GetRequest.request:type_name -> sf.substreams.foundational_store.service.v2.GetRequest
	16, // 2: sf.substreams.foundational_store_management.router.v2.GetRequest.store:type_name -> sf.substreams.foundational_store_management.router.v2.Store
	15, // 3: sf.substreams.foundational_store_management.router.v2.GetResponse.server:type_name -> sf.substreams.foundational_store_management.router.v2.Server
	1,  // 4: sf.substreams.foundational_store_management.router.v2.GetResponse.code:type_name -> sf.substreams.foundational_store_management.router.v2.GetResponse.Code
	18, // 5: sf.substreams.foundational_store_management.router.v2.GetResponse.store_response:type_name -> sf.substreams.foundational_store.service.v2.GetResponse
	15, // 6: sf.substreams.foundational_store_management.router.v2.LookupResponse.server:type_name -> sf.substreams.foundational_store_management.router.v2.Server
	16, // 7: sf.substreams.foundational_store_management.router.v2.DeployStoreRequest.store:type_name -> sf.substreams.foundational_store_management.router.v2.Store
	2,  // 8: sf.substreams.foundational_store_management.router.v2.DeployStoreResponse.code:type_name -> sf.substreams.foundational_store_management.router.v2.DeployStoreResponse.Code
	15, // 9: sf.substreams.foundational_store_management.router.v2.DeployStoreResponse.server:type_name -> sf.substreams.foundational_store_management.router.v2.Server
	15, // 10: sf.substreams.foundational_store_management.router.v2.UndeployStoreRequest.server:type_name -> sf.substreams.foundational_store_management.router.v2.Server
	3,  // 11: sf.substreams.foundational_store_management.router.v2.UndeployStoreResponse.code:type_name -> sf.substreams.foundational_store_management.router.v2.UndeployStoreResponse.Code
	4,  // 12: sf.substreams.foundational_store_management.router.v2.Server.state:type_name -> sf.substreams.foundational_store_management.router.v2.Server.State
	19, // 13: sf.substreams.foundational_store_management.router.v2.Server.last_ping_time:type_name -> google.protobuf.Timestamp
	19, // 14: sf.substreams.foundational_store_management.router.v2.Server.last_request:type_name -> google.protobuf.Timestamp
	19, // 15: sf.substreams.foundational_store_management.router.v2.Server.last_successful_request:type_name -> google.protobuf.Timestamp
	11, // 16: sf.substreams.foundational_store_management.router.v2.StoreManager.DeployStore:input_type -> sf.substreams.foundational_store_management.router.v2.DeployStoreRequest
	13, // 17: sf.substreams.foundational_store_management.router.v2.StoreManager.UndeployStore:input_type -> sf.substreams.foundational_store_management.router.v2.UndeployStoreRequest
	5,  // 18: sf.substreams.foundational_store_management.router.v2.StoreManager.Ping:input_type -> sf.substreams.foundational_store_management.router.v2.PingRequest
	7,  // 19: sf.substreams.foundational_store_management.router.v2.Router.Get:input_type -> sf.substreams.foundational_store_management.router.v2.GetRequest
	7,  // 20: sf.substreams.foundational_store_management.router.v2.Router.GetFirst:input_type -> sf.substreams.foundational_store_management.router.v2.GetRequest
	12, // 21: sf.substreams.foundational_store_management.router.v2.StoreManager.DeployStore:output_type -> sf.substreams.foundational_store_management.router.v2.DeployStoreResponse
	14, // 22: sf.substreams.foundational_store_management.router.v2.StoreManager.UndeployStore:output_type -> sf.substreams.foundational_store_management.router.v2.UndeployStoreResponse
	6,  // 23: sf.substreams.foundational_store_management.router.v2.StoreManager.Ping:output_type -> sf.substreams.foundational_store_management.router.v2.PingResponse
	8,  // 24: sf.substreams.foundational_store_management.router.v2.Router.Get:output_type -> sf.substreams.foundational_store_management.router.v2.GetResponse
	8,  // 25: sf.substreams.foundational_store_management.router.v2.Router.GetFirst:output_type -> sf.substreams.foundational_store_management.router.v2.GetResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_sf_substreams_foundational_store_management_router_v2_router_proto_init() }
func file_sf_substreams_foundational_store_management_router_v2_router_proto_init() {
	if File_sf_substreams_foundational_store_management_router_v2_router_proto != nil {
		return
	}
	file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[1].OneofWrappers = []any{}
	file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[3].OneofWrappers = []any{}
	file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[7].OneofWrappers = []any{}
	file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDesc), len(file_sf_substreams_foundational_store_management_router_v2_router_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_sf_substreams_foundational_store_management_router_v2_router_proto_goTypes,
		DependencyIndexes: file_sf_substreams_foundational_store_management_router_v2_router_proto_depIdxs,
		EnumInfos:         file_sf_substreams_foundational_store_management_router_v2_router_proto_enumTypes,
		MessageInfos:      file_sf_substreams_foundational_store_management_router_v2_router_proto_msgTypes,
	}.Build()
	File_sf_substreams_foundational_store_management_router_v2_router_proto = out.File
	file_sf_substreams_foundational_store_management_router_v2_router_proto_goTypes = nil
	file_sf_substreams_foundational_store_management_router_v2_router_proto_depIdxs = nil
}
